Repository deckhouse/sds-local-volume, pull requests merged in 2024-06, with the labels that each got.

#44 [docs] Change the module status to `preview`
  docs/README.md
  docs/README.ru.md
Labels: documentation

#46 [controller][csi] Add contiguous setting
  crds/doc-ru-localstorageclass.yaml
  crds/localstorageclass.yaml
  images/sds-local-volume-controller/api/v1alpha1/local_storage_class.go
  images/sds-local-volume-controller/pkg/controller/local_csi_node_watcher_test.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_func.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_test.go
  images/sds-local-volume-csi/api/v1alpha1/lvm_logical_volume.go
  images/sds-local-volume-csi/driver/controller.go
  images/sds-local-volume-csi/internal/const.go
  images/sds-local-volume-csi/pkg/utils/func.go
Labels: enhancement

#47 [docs] Fixes in docs
  docs/README.md
  docs/README.ru.md
Labels: documentation

#45 [controller] add pod antiaffinity rules
  templates/sds-local-volume-controller/deployment.yaml
Labels: bug
