Repository deckhouse/sds-local-volume, pull requests merged in 2024-12, with the labels that each got.

#86 [csi] CreateSnapshot implementation
  docs/FAQ.md
  images/sds-local-volume-controller/src/go.mod
  images/sds-local-volume-controller/src/go.sum
  images/sds-local-volume-csi/src/driver/controller.go
  images/sds-local-volume-csi/src/driver/node.go
  images/sds-local-volume-csi/src/go.mod
  images/sds-local-volume-csi/src/go.sum
  images/sds-local-volume-csi/src/internal/const.go
  images/sds-local-volume-csi/src/pkg/utils/func.go
  images/sds-local-volume-scheduler-extender/src/go.mod
  images/sds-local-volume-scheduler-extender/src/go.sum
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  templates/sds-local-volume-csi/controller.yaml
  templates/sds-local-volume-csi/rbac-for-us.yaml
  templates/sds-local-volume-csi/volume-snapshot-class.yaml
Labels: enhancement

#93 [ci] Update SNC package version
  images/sds-local-volume-controller/src/go.mod
  images/sds-local-volume-controller/src/go.sum
  images/sds-local-volume-csi/src/go.mod
  images/sds-local-volume-csi/src/go.sum
  images/sds-local-volume-scheduler-extender/src/go.mod
  images/sds-local-volume-scheduler-extender/src/go.sum
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
Labels: bug

#92 [docs] Editing typos of the sds-local-volume module and general refactoring of docs
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/README.md
  docs/README.ru.md
Labels: documentation

#91 [chore] Make all images distroless
  .werf/consts.yaml
  .werf/images.yaml
  .werf/python-deps.yaml
  .werf/release.yaml
  images/sds-local-volume-controller/werf.inc.yaml
  images/sds-local-volume-csi/src/driver/node.go
  images/sds-local-volume-csi/src/pkg/utils/node_store_manager.go
  images/sds-local-volume-csi/werf.inc.yaml
  images/sds-local-volume-scheduler-extender/werf.inc.yaml
  images/webhooks/werf.inc.yaml
  werf.yaml
Labels: enhancement

#94 [CI] Add secondary repo in build and SE+ version
  .github/workflows/build_prod.yml
  .github/workflows/deploy_prod.yml
Labels: enhancement

#96 [internal] Update lib-helm version
  charts/deckhouse_lib_helm-1.11.0.tgz
  charts/deckhouse_lib_helm-1.40.0.tgz
Labels: enhancement
