Repository deckhouse/sds-local-volume, pull requests merged in 2024-04, with the labels that each got.

#22 [docs] Add module documentation
  .werf/bundle.yaml
  docs/CONFIGURATION.md
  docs/CONFIGURATION.ru.md
  docs/CR.md
  docs/CR.ru.md
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/README.md
  docs/README.ru.md
  openapi/doc-ru-config-values.yaml
Labels: documentation

#23 [controller] Add cache for extender-scheduler
  images/sds-local-volume-controller/cmd/main.go
  images/sds-local-volume-scheduler-extender/Dockerfile
  images/sds-local-volume-scheduler-extender/cmd/cmd/root.go
  images/sds-local-volume-scheduler-extender/go.mod
  images/sds-local-volume-scheduler-extender/go.sum
  images/sds-local-volume-scheduler-extender/pkg/cache/cache.go
  images/sds-local-volume-scheduler-extender/pkg/cache/cache_test.go
  images/sds-local-volume-scheduler-extender/pkg/controller/lvg_watcher_cache.go
  images/sds-local-volume-scheduler-extender/pkg/controller/pvc_watcher_cache.go
  images/sds-local-volume-scheduler-extender/pkg/logger/logger.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/filter_test.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/route.go
  images/webhooks/src/go.mod
  templates/sds-local-volume-scheduler-extender/rbac-for-us.yaml
Labels: enhancement

#27 Add previous channel release version check
  .github/checkPreviousChannelRelease.sh
  .github/workflows/deploy_prod.yml
Labels: enhancement

#30 Fix KubeSchedulerConfiguration API version
  templates/sds-local-volume-scheduler-extender/configmap.yaml
Labels: bug

#31 Add user node selector for data nodes
  openapi/config-values.yaml
  templates/sds-local-volume-controller/secret.yaml
  templates/sds-local-volume-csi/controller.yaml
Labels: enhancement

#32 [controller] Fixed default Storage Class validation
  images/webhooks/src/validators/storageClassUpdate.go
  templates/webhooks/rbac-for-us.yaml
Labels: enhancement

#33 [controller] Change LVMVolumeGroup size field type from string to quantity
  images/sds-local-volume-controller/api/v1alpha1/lvm_volume_group.go
  images/sds-local-volume-csi/api/v1alpha1/lvm_volume_group.go
  images/sds-local-volume-csi/driver/controller.go
  images/sds-local-volume-csi/pkg/utils/func.go
  images/sds-local-volume-scheduler-extender/api/v1alpha1/lvm_volume_group.go
  images/sds-local-volume-scheduler-extender/pkg/controller/lvg_watcher_cache.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go
Labels: enhancement

#24 [csi] Add NodeStageVolume and NodeUnstageVolume
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go
  images/sds-local-volume-csi/driver/controller.go
  images/sds-local-volume-csi/driver/driver.go
  images/sds-local-volume-csi/driver/node.go
  images/sds-local-volume-csi/go.mod
  images/sds-local-volume-csi/go.sum
  images/sds-local-volume-csi/internal/const.go
  images/sds-local-volume-csi/internal/inflight.go
  images/sds-local-volume-csi/internal/inflight_test.go
  images/sds-local-volume-csi/pkg/utils/func.go
  images/sds-local-volume-csi/pkg/utils/node-store-manager.go
  images/sds-local-volume-csi/pkg/utils/volume.go
  templates/sds-local-volume-csi/controller.yaml
Labels: bug

#34 [controller] Add a controller to label nodes for sds-local-volume-csi
  images/sds-local-volume-controller/api/v1alpha1/sds_local_volume_config.go
  images/sds-local-volume-controller/cmd/main.go
  images/sds-local-volume-controller/go.mod
  images/sds-local-volume-controller/pkg/config/config.go
  images/sds-local-volume-controller/pkg/controller/local_csi_node_watcher.go
  images/sds-local-volume-controller/pkg/controller/local_csi_node_watcher_test.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go
Labels: enhancement

#36 [controller] Add a webhook to validate storage class operations
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/func.go
  images/webhooks/src/handlers/lscValidator.go
  images/webhooks/src/handlers/podSchedulerMutator.go
  images/webhooks/src/handlers/scValidator.go
  images/webhooks/src/main.go
  images/webhooks/werf.inc.yaml
  templates/webhooks/webhook.yaml
Labels: enhancement

#37 [controller] Add some logic refactoring and minor fixes
  images/sds-local-volume-scheduler-extender/pkg/cache/cache.go
  images/sds-local-volume-scheduler-extender/pkg/cache/cache_test.go
  images/sds-local-volume-scheduler-extender/pkg/controller/lvg_watcher_cache.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
Labels: bug
