Repository deckhouse/sds-local-volume, pull requests merged in 2024-05, with the labels that each got.

#40 [ci] Fix previous channel release check
  .github/check_previous_channel_release.sh
  .github/workflows/deploy_prod.yml
Labels: enhancement

#38 [docs] Add docs for local-csi-node-watcher controller
  crds/doc-ru-localstorageclass.yaml
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/README.md
  docs/README.ru.md
  openapi/doc-ru-config-values.yaml
Labels: documentation

#41 [ci] Fix previous release check
  .github/workflows/deploy_prod.yml
Labels: bug

#42 [ci] Fix previous release check (2)
  .github/workflows/deploy_prod.yml
Labels: bug

#39 [controller] Remove isDefault field and refactor some logic in lsc controller
  crds/doc-ru-localstorageclass.yaml
  crds/localstorageclass.yaml
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/README.md
  images/sds-local-volume-controller/Dockerfile
  images/sds-local-volume-controller/api/v1alpha1/local_storage_class.go
  images/sds-local-volume-controller/cmd/main.go
  images/sds-local-volume-controller/go.mod
  images/sds-local-volume-controller/go.sum
  images/sds-local-volume-controller/pkg/controller/controller_suite_test.go
  images/sds-local-volume-controller/pkg/controller/local_csi_node_watcher.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_func.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_test.go
  images/sds-local-volume-controller/pkg/monitoring/monitoring.go
  images/sds-local-volume-csi/driver/node.go
  images/webhooks/src/handlers/lscValidator.go
  images/webhooks/src/handlers/scValidator.go
  images/webhooks/src/v1alpha1/local_storage_class.go
Labels: enhancement
