Repository deckhouse/sds-local-volume, pull requests merged in 2024-09, with the labels that each got.

#79 [CI] Add images check with Trivy
  .github/workflows/trivy_check.yaml
  .github/workflows/trivy_image_check.yaml
  .werf/images-digests.yaml
  images/sds-local-volume-controller/werf.inc.yaml
  images/sds-local-volume-csi/Dockerfile
  images/sds-local-volume-scheduler-extender/werf.inc.yaml
  images/webhooks/werf.inc.yaml
  trivy-silent.yaml
Labels: enhancement

#81 [docs] Small docs fixes
  docs/README.md
  docs/README.ru.md
Labels: documentation

#80 [controller] Merge cmd subpackage into main
  images/sds-local-volume-csi/go.mod
  images/sds-local-volume-csi/go.sum
  images/sds-local-volume-scheduler-extender/src/cmd/access_log.go
  images/sds-local-volume-scheduler-extender/src/cmd/access_log_test.go
  images/sds-local-volume-scheduler-extender/src/cmd/cmd/root.go
  images/sds-local-volume-scheduler-extender/src/cmd/main.go
  images/sds-local-volume-scheduler-extender/src/go.mod
  images/sds-local-volume-scheduler-extender/src/go.sum
Labels: enhancement

#82 [controller] XFS support
  .github/workflows/go_modules_check.yaml
  api/v1alpha1/local_storage_class.go
  crds/doc-ru-localstorageclass.yaml
  crds/localstorageclass.yaml
  images/sds-local-volume-controller/src/go.mod
  images/sds-local-volume-controller/src/pkg/controller/local_storage_class_watcher.go
  images/sds-local-volume-controller/src/pkg/controller/local_storage_class_watcher_func.go
  images/sds-local-volume-controller/src/pkg/controller/local_storage_class_watcher_test.go
  images/sds-local-volume-controller/werf.inc.yaml
  images/sds-local-volume-csi/Dockerfile
  images/sds-local-volume-csi/src/cmd/main.go
  images/sds-local-volume-csi/src/config/config.go
  images/sds-local-volume-csi/src/driver/controller.go
  images/sds-local-volume-csi/src/driver/driver.go
  images/sds-local-volume-csi/src/driver/health.go
  images/sds-local-volume-csi/src/driver/identity.go
  images/sds-local-volume-csi/src/driver/node.go
  images/sds-local-volume-csi/src/go.mod
  images/sds-local-volume-csi/src/go.sum
  images/sds-local-volume-csi/src/internal/const.go
  images/sds-local-volume-csi/src/internal/inflight.go
  images/sds-local-volume-csi/src/internal/inflight_test.go
  images/sds-local-volume-csi/src/pkg/kubutils/kubernetes.go
  images/sds-local-volume-csi/src/pkg/logger/logger.go
  images/sds-local-volume-csi/src/pkg/utils/func.go
  images/sds-local-volume-csi/src/pkg/utils/node_store_maganer_test.go
  images/sds-local-volume-csi/src/pkg/utils/node_store_manager.go
  images/sds-local-volume-csi/src/pkg/utils/type.go
  images/sds-local-volume-csi/werf.inc.yaml
  images/sds-local-volume-scheduler-extender/werf.inc.yaml
  images/webhooks/werf.inc.yaml
Labels: enhancement

#83 [controller] Update sds-node-configuration api version
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/README.md
  docs/README.ru.md
  images/sds-local-volume-controller/src/go.mod
  images/sds-local-volume-controller/src/go.sum
  images/sds-local-volume-controller/src/pkg/controller/local_csi_node_watcher.go
  images/sds-local-volume-controller/src/pkg/controller/local_csi_node_watcher_test.go
  images/sds-local-volume-controller/src/pkg/controller/local_storage_class_watcher_func.go
  images/sds-local-volume-controller/src/pkg/controller/local_storage_class_watcher_test.go
  images/sds-local-volume-csi/src/driver/controller.go
  images/sds-local-volume-csi/src/go.mod
  images/sds-local-volume-csi/src/go.sum
  images/sds-local-volume-csi/src/internal/const.go
  images/sds-local-volume-csi/src/pkg/utils/func.go
  images/sds-local-volume-scheduler-extender/src/go.mod
  images/sds-local-volume-scheduler-extender/src/go.sum
  images/sds-local-volume-scheduler-extender/src/pkg/cache/cache.go
  images/sds-local-volume-scheduler-extender/src/pkg/cache/cache_test.go
  images/sds-local-volume-scheduler-extender/src/pkg/consts/consts.go
  images/sds-local-volume-scheduler-extender/src/pkg/controller/lvg_watcher_cache.go
  images/sds-local-volume-scheduler-extender/src/pkg/controller/lvg_watcher_cache_test.go
  images/sds-local-volume-scheduler-extender/src/pkg/scheduler/filter.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  images/webhooks/src/handlers/lscValidator.go
Labels: enhancement

#84 [controller] Fix the cache freezed Bound PVC
  images/sds-local-volume-controller/src/go.mod
  images/sds-local-volume-controller/src/go.sum
  images/sds-local-volume-csi/src/go.mod
  images/sds-local-volume-csi/src/go.sum
  images/sds-local-volume-scheduler-extender/src/cmd/main.go
  images/sds-local-volume-scheduler-extender/src/config/config.go
  images/sds-local-volume-scheduler-extender/src/go.mod
  images/sds-local-volume-scheduler-extender/src/go.sum
  images/sds-local-volume-scheduler-extender/src/pkg/cache/cache.go
  images/sds-local-volume-scheduler-extender/src/pkg/cache/cache_test.go
  images/sds-local-volume-scheduler-extender/src/pkg/controller/lvg_watcher_cache.go
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
Labels: bug
