Repository deckhouse/sds-local-volume, pull requests merged in 2024-03, with the labels that each got.

#12 [controller] Add spec.lvm to a LocalStorageClass resource
  crds/localstorageclass.yaml
  images/sds-local-volume-controller/api/v1alpha1/local_storage_class.go
  images/sds-local-volume-controller/cmd/main.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go
  images/sds-local-volume-csi/driver/controller.go
  images/sds-local-volume-csi/internal/const.go
Labels: enhancement

#18 [csi] Add field ActualLVNameOnTheNode. Add SDSLocalVolumeCSIFinalizer. Add delete LVMLogicalVolume after error in CreateVolume. Bump go builder to 1.21
  images/sds-local-volume-csi/Dockerfile
  images/sds-local-volume-csi/api/v1alpha1/lvm_logical_volume.go
  images/sds-local-volume-csi/driver/controller.go
  images/sds-local-volume-csi/pkg/utils/func.go
Labels: enhancement

#14 [controller] Fixed free space calculation logic for PVCs using the same storage class
  images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go
Labels: bug

#17 [contoller] Add a possibility to edit a LocalStorageClass spec.lvm.LVMVolumeGroups to configure an appropriate Storage Class.
  crds/localstorageclass.yaml
  images/sds-local-volume-controller/cmd/main.go
  images/sds-local-volume-controller/pkg/config/config.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go
Labels: enhancement

#16 [docs] Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 [docs] Add Issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#19 [controller] Fix max volumes per node and R/W map
  images/sds-local-volume-csi/driver/node.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
Labels: bug

#20 [controller] Add LocalStorageClass validation webhook
  images/webhooks/src/main.go
  images/webhooks/src/v1alpha1/local_storage_class.go
  images/webhooks/src/v1alpha1/lvm_volume_group.go
  images/webhooks/src/v1alpha1/register.go
  images/webhooks/src/v1alpha1/zz_generated.deepcopy.go
  images/webhooks/src/validators/storageClassUpdate.go
  templates/webhooks/webhook.yaml
Labels: enhancement

#21 [controller] Add logs and upgrading node scoring
  images/sds-local-volume-scheduler-extender/go.mod
  images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go
  images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize_test.go
  openapi/config-values.yaml
  templates/sds-local-volume-scheduler-extender/configmap.yaml
Labels: enhancement
