Repository deckhouse/sds-local-volume, pull requests merged in 2025-02, with the labels that each got.

#100 [ci] dev in tag fix (automatic)
  templates/sds-local-volume-scheduler-extender/configmap.yaml
  templates/sds-local-volume-scheduler-extender/deployment.yaml
  templates/sds-local-volume-scheduler-extender/kube-scheduler-webhook-configuration.yaml
  templates/sds-local-volume-scheduler-extender/service.yaml
  templates/webhooks/webhook.yaml
Labels: enhancement

#101 [docs] fixed moduletag
  docs/README.md
  docs/README.ru.md
Labels: documentation

#95 Move Snapshot capabilities to EE
  .github/workflows/build_dev.yml
  .github/workflows/build_prod.yml
  .github/workflows/deploy_prod.yml
  .github/workflows/go_lint.yaml
  .github/workflows/go_modules_check.yaml
  .github/workflows/go_tests.yaml
  .github/workflows/trivy_image_check.yaml
  .golangci.yaml
  .werf/bundle.yaml
  .werf/choose-edition.yaml
  .werf/consts.yaml
  images/sds-local-volume-csi/src/driver/controller.go
  images/sds-local-volume-csi/src/driver/controller_snapshots_ee.go
  images/sds-local-volume-csi/src/go.mod
  images/sds-local-volume-csi/src/go.sum
  images/sds-local-volume-csi/werf.inc.yaml
  lib/go/common/go.mod
  lib/go/common/go.sum
  lib/go/common/pkg/feature/const_ce.go
  lib/go/common/pkg/feature/const_csepro.go
  lib/go/common/pkg/feature/const_ee.go
  lib/go/common/pkg/feature/const_se.go
  lib/go/common/pkg/feature/const_seplus.go
  lib/go/common/pkg/feature/feature.go
  openapi/values_ce.yaml
  openapi/values_ee.yaml
  templates/sds-local-volume-csi/controller.yaml
  werf-giterminism.yaml
  werf.yaml
Labels: enhancement

#104 [csi] Add a separate ServiceAccount for the csi-node
  images/sds-local-volume-controller/src/go.mod
  images/sds-local-volume-controller/src/go.sum
  images/sds-local-volume-csi/src/go.mod
  images/sds-local-volume-csi/src/go.sum
  images/sds-local-volume-csi/src/pkg/kubutils/kubernetes.go
  images/sds-local-volume-scheduler-extender/src/go.mod
  images/sds-local-volume-scheduler-extender/src/go.sum
  images/webhooks/src/go.mod
  images/webhooks/src/go.sum
  templates/sds-local-volume-csi/controller.yaml
  templates/sds-local-volume-csi/rbac-for-us.yaml
Labels: bug
