Repository deckhouse/sds-local-volume, pull requests merged in 2025-07, with the labels that each got.

#124 [internal] fix snapshotter container presence in CE version
  templates/csi/controller.yaml
Labels: bug

#126 [internal] fix snapshot prefix name
  .dmtlint.yaml
  charts/deckhouse_lib_helm-1.62.2.tgz
  charts/deckhouse_lib_helm-1.63.0.tgz
  templates/csi/controller.yaml
Labels: bug

#127 [internal] add volumesnapshotclassname annotations to storageclasses
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_func.go
  images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_test.go
  images/sds-local-volume-controller/pkg/internal/const.go
Labels: enhancement

#128 [docs] Small fixes about thin, thick volumes
  docs/FAQ.md
  docs/FAQ.ru.md
  docs/README.md
  docs/README.ru.md
Labels: documentation
